services:
  db:
    image: mysql:8.0
    container_name: soc_mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  web:
    build: .
    container_name: soc_flask
    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "5001:5000"

    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      FLASK_ENV: production

volumes:
  mysql_data: